### PR TITLE
WIP: 2.11.0-RC1 relates notes: breaking changes and deprecations

### PR DESCRIPTION
**Pull request by adriaanm**
Will make a more comprehensive pass next week.

### CODE REVIEW

**Comment by xeno-by** [comment]
Could you also put a link to reflection/macro announcement somewhere? I can post it to scalamacros.org shortly before this PR is merged.

**Comment by adriaanm** [comment]
Gladly! Could you add a comment here to propose a paragraph?

**Comment by xeno-by** [comment]
https://github.com/adriaanm/make-release-notes/pull/1

**Comment by gkossakowski** [comment]
@adriaanm: we should also mention pretty printing of ASTs added to Scala 2.11: https://github.com/scala/scala/pull/3321

It's important for tool writers like IDEs, code formatting tools, etc.

**Comment by adriaanm** [comment]
will do

**Comment by adriaanm** [comment]
ping @gkossakowski for any final additions

**Pull request merged**
