### PR TITLE
overhaul the 2.12 release announcement

### PR DESCRIPTION
**Pull request by SethTisue**
along the same lines as it was overhauled for 2.11.7

### CODE REVIEW

**Comment by lrytz** [comment]
@SethTisue sorry about this, but i have a WIP that i didn't push here / didn't create a PR for yet... it basically merges 2.11 into 2.12 (except for hand-written and other files where it doesn't make sense), and there's a small patch to hand-written. it doesn't seem to conflict much with your changes, so that's good. https://github.com/lrytz/make-release-notes/commits/2.12.x

**Comment by lrytz** [comment]
your change removes the "Binary Compatibility" section - this needs to go somewhere though. Did you intend a separate document for that?

**Comment by SethTisue** [comment]
re: binary compatibility, I think the old announcement went into too much detail about this. the new announcement gives a high level summary and links to the 2.11.1 notes for detail. by 2.12 final we should do better than that, but still keeping it in a separate document. (now tracked as #151)

**Comment by SethTisue** [comment]
I merged your changes to `hand-written.md`. (If you have changes to other files, please make a separate PR.)

**Comment by lrytz** [comment]
looks good!

**Pull request merged**
