### PR TITLE
add spark and its Twitter-based deps

### PR DESCRIPTION
**Pull request by SethTisue**
@martijnhoekstra does this seem more or less right to you?
doesn't have to be perfect, we can refine from here

### CODE REVIEW

**Review by martijnhoekstra — APPROVED** [review]
Looks about correct.

The actual build matrix of the twitter stuff is more complicated, where some (sub) projects may depend on other (sub) projects -- the twitter build script, dodo, has the more fine-grained info.

**Comment by johnynek** [comment]
Thanks...

One problem is that I have left twitter, and those projects don't have active owners at twitter, unfortunately...

I think the right idea is to reverse the dependency arrows: algebird-util should move to the util repo. bijection-scrooge, should move to scrooge (or be removed)...

Anyone can make these PRs.... I can say I will try to, but realistically I'm moving slowly. I use 2.11 at work. I'd love to get to 2.12 in a year or so, 2.13 is like 4 years away for me, so this isn't a super high priority.

**Comment by SethTisue** [comment]
thx Oscar for the update

FYI @cacoco

**Comment by johnynek** [comment]
BTW: spark just depends on chill core, not all the modules. So you could probably add some minimally hacked build of chill that doesn't depend on algebird or bijection.

Side note, it would be really nice if making repos, publishing and CI were easier, because all of these joint modules (chill-algebird, algebird-bijection....) should really be new projects that depend on the core of both. Forcing them into one or the other puts a dependency which complicates things. Especially since most users don't use those submodules.

Maybe some better tooling around the new github CI + artifact serving could bring down the cost of making new scala repos by an order of magnitude. That is what we need to make it more manageable for a single person to be running 10-100 repos, as seems like what we need to have small libraries in scala (since we have a small supply of OSS contributors).

**Comment by martijnhoekstra** [comment]
I'm happy to explore pulling apart projects if github CI and artefact serving is going to support that, but no idea what that's going to look like. As a community contributor, it's really not that easy to pull apart and set up CI that's going to need re-setting-up by twitter anyway.

Pulled apart repos does require more bincompat/semver discipline though: if you break bincompat of the core modules every other week, and have to re-publish all joint modules depending on it, you're going to have a bad time. Then again, if you can relatively freely make a breaking change in a joint module without having your downstream users having to check if they should and can update the entire library that would be much nicer again.

**Pull request merged**
