### PR TITLE
Update hand-written.md

### PR DESCRIPTION
**Pull request by peter-empen**

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks!

**Comment by peter-empen** [comment]
Thanks too, Adriaan. Starting at
http://scala-lang.org/download/2.11.0.htmlhow can one navigate to the
list of community libraries edited on Github?

2014-04-25 18:48 GMT+02:00 Adriaan Moors notifications@github.com:

**Comment by adriaanm** [comment]
Great idea. We should find a way to publish this easily.

**Comment by adriaanm** [comment]
@heathermiller what do you think is the easiest way of advertising this (changing) list of available community libraries?

**Pull request merged**
