### PR TITLE
Add scala-continuations section

### PR DESCRIPTION
**Pull request by danslapman**

### CODE REVIEW

**Comment by SethTisue** [comment]
I don't think we can spare this much space for instructions for one project. Can you reduce it to a one-line addition, and assume that people who are interested in scala-continuations will consult the repo for details?

**Comment by SethTisue** [comment]
also, neither the library nor the plugin seems to be on Maven Central:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-lang.plugins#scala-continuations-library_2.12.0-RC2;1.0.3-RC3: not found
[warn]  :: org.scala-lang.plugins#scala-continuations-plugin_2.12.0-RC2;1.0.3-RC3: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by SethTisue** [comment]
according to https://github.com/scala/scala-continuations/issues/14 the artifacts are on their way to Maven Central right now

**Comment by danslapman** [comment]
Seems that @adriaanm did this already.

**Pull request closed without merging**
