### PR TITLE
2.10.4-RC3

### PR DESCRIPTION
**Pull request by gkossakowski**

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @retronym.

**Comment by retronym** [comment]
This filter is not public, you need to share it: https://issues.scala-lang.org/issues/?filter=12416

**Comment by retronym** [comment]
Same for https://issues.scala-lang.org/issues/?filter=12417

**Comment by retronym** [comment]
The new "rendered-diff" GitHub feature rocks!

LGTM aside from the JIRA permissions.

**Comment by gkossakowski** [comment]
Oh wow! I didn't know about the rendered diff thingy. It looks great!

The JIRA permissions should be fixed. Could you check?

**Comment by retronym** [comment]
Nope, still private.

**Comment by retronym** [comment]
image

**Comment by gkossakowski** [comment]
JIRA UI beat me. I see what you see on the screenshot now but let's double check.

**Comment by gkossakowski** [comment]
Nvm, I realized I could just check with incognito mode. Merging.

**Pull request merged**
