### PR TITLE
Dedup pending by referencing the community build wiki page

### PR DESCRIPTION
**Pull request by dwijnand**
WDYT?

### CODE REVIEW

**Comment by SethTisue** [comment]
being published for M4, and being green in the community build, are two different things, highly correlated to be sure, but not the same. I don't think we can collapse the distinction. users only care about what's been published.

**Comment by dwijnand** [comment]
But this is the pending section, not the "has been published for M4" section.

It enumerates a subset of the projects which still need to be cross-built and published, which I feel for small projects are done as a single unit of work.

**Comment by SethTisue** [comment]
I'm sorry but I just don't understand your goal here. It seems to me that this change makes this page less valuable for end users. But maybe I just don't get it? I don't see how "It enumerates a subset of the projects which still need to be cross-built and published, which I feel for small projects are done as a single unit of work" is even an argument for this change.

**Comment by dwijnand** [comment]
Sure, let me explain my reasoning.

To support 2.13.0-M4 you need to first make the code compile with 2.13.0-M4 and then publish that. The community build only needs the former, while everyone else needs the published jars. I feel like most of the time this is done as a single unit of work, and we're effectively tracking it in the wiki page, and therefore we have a second (sub) set of these here. Indeed, IIRC from checking them yesterday, some of the links here are no longer pending.

Anyways, it's probably not worth the time it's taken to explain it. I'll send another PR to update this list.

**Comment by dwijnand** [comment]
... aaand nothing turned out to need updating. 🙂

**Pull request closed without merging**
