### PR TITLE
Mention Scala.js

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by retronym** [comment]
@sjrd @adriaanm  WDYT? I didn't get this merged in time for the email announcement, but I can still update the release notes on the web site.

**Comment by sjrd** [comment]
I upvote ;-) But ultimately you guys are better placed than me to decide whether it is appropriate.
The wording seems alright to me.

**Comment by adriaanm** [comment]
Yep, I think we should include it!

**Comment by adriaanm** [comment]
I'll rebase and merge and synch to scala-lang

**Comment by sjrd** [comment]
Thanks :)

**Pull request closed without merging**
