### PR TITLE
Release notes for 2.11.2

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @adriaanm @gkossakowski @retronym 

Rendered version: https://github.com/lrytz/make-release-notes/blob/2.11.2/hand-written.md

**Comment by adriaanm** [comment]
Modulo "is is", LGTM!

**Comment by retronym** [comment]
I wonder if we should take this opportunity to rationalize the release notes.
- Intro
- link out to 2.11.{0, ... N-1} release notes
- Highlights and details for this release.

**Comment by adriaanm** [comment]
Sounds good to me. A good opportunity to spin off the "released OSS
projects list"

**Comment by lrytz** [comment]
ok, will do.

**Comment by lrytz** [comment]
OK, updated, please check again: https://github.com/lrytz/make-release-notes/blob/2.11.2/hand-written.md

**Comment by adriaanm** [comment]
I would also give our old list of projects a new home for now, since I don't think it;s completely subsumed by the links you give. It can just be a separate projects-2.11.md in this repo that can be updated as before with PRs and we just link to the rendered version

**Comment by lrytz** [comment]
OK, no problem.

**Comment by lrytz** [comment]
Added the list. The link in the release notes is broken until we merge this PR, but it's here: https://github.com/lrytz/make-release-notes/blob/2.11.2/projects-2.11.md

**Comment by gourlaysama** [comment]
Maybe this is the time to mention that

```
git log --no-merges --oneline v2.11.2 --not v2.11.1 --format='%aN' | sort | uniq -c | sort -rn
```

is just a _very_ convoluted way of writing 

```
git shortlog -sn --no-merges v2.11.1..v2.11.2
```

Output is the same (actually, better: people with the same number of commits are listed in alphabetical order instead of reverse alphabetical order)

**Comment by lrytz** [comment]
@gourlaysama updated, thanks

**Pull request merged**
