### PR TITLE
Add hooks for non-scala projects to use the git-info structure we have.

### PR DESCRIPTION
**Pull request by jsuereth**
particularly EVERY sbt-related project which uses the default github stuffs,
including  main method that will generate basic release notes for sbt projects.

Review @adriaanm or @retronym or @gkossakowski

### CODE REVIEW

**Comment by muuki88** [comment]
+1

**Comment by gkossakowski** [comment]
What kind of problem does this PR tries to solve?

**Comment by adriaanm** [comment]
ping @jsuereth

**Comment by jsuereth** [comment]
This tries to make it so I can use the make-release notes generator to generate release notes for small sbt-projects as well, including sbt itself.  We used it for sbt/sbt-native-packager + sbt/sbt previous releases.

**Comment by muuki88** [comment]
Can I help on any details here? We really want to use this project for our release notes and currently doing this with the code in this pr.

**Comment by adriaanm** [comment]
I'm torn on this one. I want this repo to focus on generating the Scala release notes, and this PR doesn't really help us with that. We've moved away from the old generator because I don't like the verbosity of the release notes it produces. Long lists of commits are available on github, and lists of issues are on jira. The notes should summarize.

Given this difference in requirements, I think it's better to split up the projects: one that continues in the original tradition and potentially generalizes it, and one that focuses on the style we prefer. The Scala team doesn't have the resources to maintain a full-fledged, all-purpose release note generator, sorry.

**Comment by muuki88** [comment]
Thanks for the info :) We'll fork this and try to build up a small community.

**Pull request closed without merging**
