### PR TITLE
bye bye Travis-CI, hello GitHub Actions

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
also merged forward onto 2.13.x

**Comment by som-snytt** [comment]
Travis has given me its last red ex. ❌

**Comment by SethTisue** [comment]
https://app.travis-ci.com/github/scala shows some repos you can still PR to when you're feeling nostalgic and want to hang out with your old buddy.

**Comment by som-snytt** [comment]
I wonder if continuations has a maintainer yet.

**Pull request merged**
