### PR TITLE
Scala 2.11.8 release notes

### PR DESCRIPTION
**Pull request by SethTisue**
(I'll merge at release time)

review by @adriaanm especially (add some of your customary fizz and sparkles, eh?) & by all

### CODE REVIEW

**Comment by som-snytt** [comment]
Maybe mention the other, more secret handshake:

```
scala> for (x <- 1 to 10) println(x) //print

scala.Predef.intWrapper(1).to(10).foreach[Unit](((x: Int) => scala.Predef.println(x))) // : Unit

scala> for (x <- 1 to 10) println(x) //typeAt 12 12
   (end: Int)scala.collection.immutable.Range.Inclusive
```

**Comment by adriaanm** [comment]
LGTM

**Comment by SethTisue** [comment]
> Maybe mention the other, more secret handshake

@som-snytt falls under the https://issues.scala-lang.org/browse/SI-7900 umbrella, I think

**Comment by som-snytt** [comment]
@SethTisue ha, ha, consider me zinged.

**Pull request merged**
