### PR TITLE
adding links to Scaladex for 2.12.0

### PR DESCRIPTION
**Pull request by MasseGuillaume**
there is no distinction between 2.12.0 and 2.12.0-RC2 see https://github.com/scalacenter/scaladex/issues/284

### CODE REVIEW

**Comment by SethTisue** [comment]
thanks Guillaume!

I'm going to merge this, then send a new PR proposing a little bit different way of handling this

**Comment by SethTisue** [comment]
my revised version: https://github.com/scala/make-release-notes/pull/227

**Comment by lrytz** [comment]
@MasseGuillaume I might be missing something: I just clicked on https://index.scala-lang.org/search?q=targets%3Ascala_2.12, then went on some project in that list randomly (https://index.scala-lang.org/dvreeze/yaidom), then in the dropdown for Scala versions, there's only 2.11 and 2.10, but not 2.12

**Comment by MasseGuillaume** [comment]
@lrytz 

https://index.scala-lang.org/dvreeze/yaidom/yaidom/1.6.0-M6

it's because we select the latest non pre-released version (eg 1.5.1 not 1.6.0-M6)

**Comment by lrytz** [comment]
ok,  thank you. but then this one only has binary version 2.12.0-RC1, not
2.12. also,  it would be great if one could easily find all releases if a
library that are built for a specific scala binary version

On Nov 3, 2016 22:07, "Guillaume Massé" notifications@github.com wrote:

@lrytz https://github.com/lrytz

https://index.scala-lang.org/dvreeze/yaidom/yaidom/1.6.0-M6

it's because we select the latest non pre-released version (eg 1.5.1 not
1.6.0-M6)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/scala/make-release-notes/pull/222#issuecomment-258274274,
or mute the thread

**Comment by MasseGuillaume** [comment]
@lrytz yep: https://github.com/scalacenter/scaladex/issues/284

**Pull request merged**
